# Generated by Django 3.1 on 2020-08-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='classification',
            field=models.IntegerField(choices=[(0, 'Student'), (4, 'Admin'), (2, 'Work Study'), (1, 'Mentor'), (3, 'Master Teacher')], default=0),
        ),
    ]
