# Generated by Django 3.1 on 2020-08-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200808_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='classification',
            field=models.IntegerField(choices=[(4, 'Admin'), (3, 'Master Teacher'), (0, 'Student'), (2, 'Work Study'), (1, 'Mentor')], default=0),
        ),
    ]
