# Generated by Django 3.1 on 2020-08-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200808_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='classification',
            field=models.IntegerField(choices=[(3, 'Master Teacher'), (4, 'Admin'), (2, 'Work Study'), (1, 'Mentor'), (0, 'Student')], default=0),
        ),
    ]
