# Generated by Django 3.1 on 2020-08-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200808_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='classification',
            field=models.IntegerField(choices=[(1, 'Mentor'), (2, 'Work Study'), (4, 'Admin'), (3, 'Master Teacher'), (0, 'Student')], default=0),
        ),
    ]
