# Generated by Django 3.1 on 2020-08-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200808_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='classification',
            field=models.IntegerField(choices=[(1, 'Mentor'), (2, 'Work Study'), (3, 'Master Teacher'), (0, 'Student'), (4, 'Admin')], default=0),
        ),
    ]
