# Generated by Django 3.1 on 2020-08-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200811_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='classification',
            field=models.IntegerField(choices=[(2, 'Work Study'), (0, 'Student'), (4, 'Admin'), (3, 'Master Teacher'), (1, 'Mentor')], default=0),
        ),
    ]
