# Generated by Django 3.1 on 2020-08-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200817_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='classification',
            field=models.IntegerField(choices=[(0, 'Student'), (1, 'Mentor'), (4, 'Admin'), (3, 'Master Teacher'), (2, 'Work Study')], default=0),
        ),
    ]
