# Generated by Django 3.1 on 2020-08-08 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_number', models.IntegerField(unique=True)),
                ('status', models.IntegerField(choices=[(3, 'UPDATED'), (9, 'DONE'), (0, 'ASSIGNED'), (4, 'FILLED'), (6, 'OUT'), (5, 'SELF-FILLED'), (8, 'EMPTIED'), (7, 'RETURNED'), (1, 'STARTED'), (2, 'PLACED')], default=0)),
                ('trello_id', models.CharField(blank=True, max_length=50)),
                ('expected_pickup_datetime', models.DateTimeField(blank=True, null=True)),
                ('actual_pickup_datetime', models.DateTimeField(blank=True, null=True)),
                ('expected_return_datetime', models.DateTimeField(blank=True, null=True)),
                ('actual_return_datetime', models.DateTimeField(blank=True, null=True)),
                ('other_notes', models.TextField(blank=True, null=True)),
                ('master_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('order_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('other_notes', models.TextField(blank=True, null=True)),
                ('self_filled', models.BooleanField(default=False)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
