# Generated by Django 3.1 on 2020-08-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercontent',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordermember',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='content',
            field=models.ManyToManyField(to='orders.OrderContent'),
        ),
        migrations.AddField(
            model_name='order',
            name='members',
            field=models.ManyToManyField(to='orders.OrderMember'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'STARTED'), (2, 'PLACED'), (4, 'FILLED'), (5, 'SELF-FILLED'), (6, 'OUT'), (9, 'DONE'), (7, 'RETURNED'), (3, 'UPDATED'), (8, 'EMPTIED'), (0, 'ASSIGNED')], default=0),
        ),
    ]
