# Generated by Django 3.1 on 2020-08-08 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200808_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='content',
        ),
        migrations.RemoveField(
            model_name='order',
            name='members',
        ),
        migrations.AddField(
            model_name='ordercontent',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='ordermember',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(2, 'PLACED'), (7, 'RETURNED'), (6, 'OUT'), (0, 'ASSIGNED'), (9, 'DONE'), (5, 'SELF-FILLED'), (4, 'FILLED'), (1, 'STARTED'), (3, 'UPDATED'), (8, 'EMPTIED')], default=0),
        ),
    ]
