# Generated by Django 3.1 on 2020-08-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200808_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(4, 'FILLED'), (6, 'OUT'), (7, 'RETURNED'), (1, 'STARTED'), (5, 'SELF-FILLED'), (8, 'EMPTIED'), (0, 'ASSIGNED'), (2, 'PLACED'), (3, 'UPDATED'), (9, 'DONE')], default=0),
        ),
    ]
