# Generated by Django 3.1 on 2020-08-12 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_auto_20200811_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'ASSIGNED'), (5, 'SELF-FILLED'), (9, 'DONE'), (3, 'UPDATED'), (4, 'FILLED'), (2, 'PLACED'), (1, 'STARTED'), (6, 'OUT'), (7, 'RETURNED'), (8, 'EMPTIED')], default=0),
        ),
        migrations.DeleteModel(
            name='OrderMember',
        ),
    ]
