# Generated by Django 3.1 on 2020-08-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200817_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UPDATED', 'UPDATED'), ('OUT', 'OUT'), ('SELF-FILLED', 'SELF-FILLED'), ('PLACED', 'PLACED'), ('FILLED', 'FILLED'), ('RETURNED', 'RETURNED'), ('EMPTIED', 'EMPTIED'), ('DONE', 'DONE'), ('STARTED', 'STARTED'), ('ASSIGNED', 'ASSIGNED')], default='ASSIGNED', max_length=11),
        ),
    ]
